// Code generated by MockGen. DO NOT EDIT.
// Source: usecase.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	libpagination "shop-service/internal/util/libpagination"
	entity "shop-service/module/shop/entity"

	gomock "github.com/golang/mock/gomock"
)

// MockShopUsecase is a mock of ShopUsecase interface.
type MockShopUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockShopUsecaseMockRecorder
}

// MockShopUsecaseMockRecorder is the mock recorder for MockShopUsecase.
type MockShopUsecaseMockRecorder struct {
	mock *MockShopUsecase
}

// NewMockShopUsecase creates a new mock instance.
func NewMockShopUsecase(ctrl *gomock.Controller) *MockShopUsecase {
	mock := &MockShopUsecase{ctrl: ctrl}
	mock.recorder = &MockShopUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShopUsecase) EXPECT() *MockShopUsecaseMockRecorder {
	return m.recorder
}

// ListByParams mocks base method.
func (m *MockShopUsecase) ListByParams(ctx context.Context, params *entity.ListShopByParams) ([]*entity.Shop, *libpagination.OffsetPagination, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByParams", ctx, params)
	ret0, _ := ret[0].([]*entity.Shop)
	ret1, _ := ret[1].(*libpagination.OffsetPagination)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListByParams indicates an expected call of ListByParams.
func (mr *MockShopUsecaseMockRecorder) ListByParams(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByParams", reflect.TypeOf((*MockShopUsecase)(nil).ListByParams), ctx, params)
}
